### ISSUE TITLE
ESP32 reboot when change switch state in Home assistant

### ISSUE THREAD

**Issue by Tigui91racing** [millskyle/BRMesh_homeassistant#2]
Hi,

I got a problem, when I change the state of the button in Home Assistant, the ESP32 get an error and reboot, here's what I see in the arduino serial monitor when I change state of the light in Home Assistant
---------------------------------------------------------------------------------------------------------------------------------------------------
State: 1
data: 220180000000
CORRUPT HEAP: Bad head at 0x3ffce414. Expected 0xabba1234 got 0x3ffce440

assert failed: multi_heap_free multi_heap_poisoning.c:276 (head != NULL)

Backtrace: 0x400826fd:0x3ffd5110 0x400941f1:0x3ffd5130 0x400997ae:0x3ffd5150 0x40098939:0x3ffd5280 0x40083776:0x3ffd52a0 0x400997ed:0x3ffd52c0 0x4011b366:0x3ffd52e0 0x4011b3b4:0x3ffd5300 0x40145c59:0x3ffd5360 0x40148a15:0x3ffd5380 0x40096aee:0x3ffd53b0

ELF file SHA256: f699be09cc140aaa

Rebooting...
--------------------------------------------------------------------------------------------------------------------------------------------------

after doing some test, my Mac adress when I check the serial monitor, is 8C:34:25:5C:7B:CC but when I check with my wifi, it's CC:7B:5C:25:34:8C 

When I put mac like my wifi see it, In home assistant, I got iBeacon Tracker that appeared, installed it, when I change a switch state, serial monitor show nothing and do not have memory error

also where do I input my light ID ?

Thanks

**Comment by BitStab** [comment]
Did my setup today and ran into the same issue. The mac address returned by the serial interface seems inverted back to front. But i already have the right one, because i took it already on the first install from my dhcp server. Anyway i have the reboot issue on interaction with the lights:

`State: 1
data: 220180000000
CORRUPT HEAP: Bad head at 0x3ffce1a4. Expected 0xabba1234 got 0x3ffce1d0

assert failed: multi_heap_free multi_heap_poisoning.c:276 (head != NULL)


Backtrace: 0x400826fd:0x3ffd4ff0 0x400941f1:0x3ffd5010 0x400997ae:0x3ffd5030 0x40098939:0x3ffd5160 0x40083776:0x3ffd5180 0x400997ed:0x3ffd51a0 0x4011b1d2:0x3ffd51c0 0x4011b220:0x3ffd51e0 0x40145ac5:0x3ffd5240 0x40148881:0x3ffd5260 0x40096aee:0x3ffd5290




ELF file SHA256: a255dca9f3067727

Rebooting...
`

I'll try to dig a little into it, but i'm absolutely no esp32 or arduino main dev ^^

**Comment by BitStab** [comment]
Ok, i got ahead of things!

In the Board Manager of the Arduino IDE I have downgraded esp32 Boards to version 2.0.10 - after this the code seems to work.
I also tested the [fork](https://github.com/nanobyte84/BRMesh_homeassistant/blob/main/brmesh/brmesh.ino) by @nanobyte84 which includes light groups and is a well cleaned up piece of code. Maybe he should do a PR over here, would make things easier.

**Comment by Tigui91racing** [comment]
> Ok, i got ahead of things!
> 
> In the Board Manager of the Arduino IDE I have **downgraded esp32 Boards to version 2.0.10** - after this the code seems to work. I also tested the [fork](https://github.com/nanobyte84/BRMesh_homeassistant/blob/main/brmesh/brmesh.ino) by @nanobyte84 which includes light groups and is a well cleaned up piece of code. Maybe he should do a PR over here, would make things easier.

I got the fork you mentioned, it work !!!!!!!!Thanks

**Comment by BitStab** [comment]
> > Ok, i got ahead of things!
> > In the Board Manager of the Arduino IDE I have **downgraded esp32 Boards to version 2.0.10** - after this the code seems to work. I also tested the [fork](https://github.com/nanobyte84/BRMesh_homeassistant/blob/main/brmesh/brmesh.ino) by @nanobyte84 which includes light groups and is a well cleaned up piece of code. Maybe he should do a PR over here, would make things easier.
> 
> I got the fork you mentioned, it work !!!!!!!!Thanks

You're welcome!

@millskyle maybe you adapt the readme, adding the neccessary board library version to make the build work? Don't get me wrong, you did great work getting this thing together and it works awesome - but only if you know about these things.

**Comment by millskyle** [comment]
Thanks for tracking this down! I've added a note to the README.

**Comment by millskyle** [comment]
Resolved with downgrade of esp board core.
